name: Build Unreal Engine 5

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Unreal Engine 5 Project
        uses: Fork-on-the-Table-Collective/UE5-build-action@v1.0
        with:
          enginePath: 'C:/EpicGames/UE_5.5'
          uprojectPath: 'GraduationWork.uproject'
          buildConfig: 'Shipping'
          platform: 'Win64'
          clean: 'true'
          cook: 'true'
          compressed: 'true'
          UpdateIfNeeded: 'true'
          stage: 'true'
          package: 'false'
          pak: 'false'
          server: 'false'
          archive: 'false'
          archivePath: ''
          nullrhi: 'false'
          editor: 'true'
          encryptIniFiles: 'false'
          release: '1.0.0'
          patch: '1.0.1'
          maps: 'Map1,Map2'
          deletePDB: 'false'
          anticheatEnabled: 'true'
          anticheatPrivateKey: 'base64-private-key'
          anticheatPublicCert: 'base64-public-cert'
